/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore list.
// It is generated by the `expo` package and is used to provide type declarations
// for Expo specific globals (like __DEV__) and module types.

// React Native global declarations
declare const __DEV__: boolean;
declare const __EXPO_ENV__: string | undefined;
