// Type definitions for Lumio app
import type { ComponentProps } from 'react';
import type { Ionicons } from '@expo/vector-icons';

/**
 * Strongly-typed Ionicons icon name.
 * Eliminates `as any` casts throughout the codebase.
 */
export type IconName = ComponentProps<typeof Ionicons>['name'];

export type ContentType =
  | 'link'
  | 'article'
  | 'video'
  | 'recipe'
  | 'book'
  | 'movie'
  | 'workout'
  | 'place'
  | 'restaurant'
  | 'tool'
  | 'idea'
  | 'travel'
  | 'social'
  | 'podcast'
  | 'course'
  | 'product';

/** Detected source platform for a saved URL. */
export type UrlSource =
  | 'instagram'
  | 'youtube'
  | 'twitter'
  | 'linkedin'
  | 'medium'
  | 'spotify'
  | 'amazon'
  | 'news'
  | 'blog'
  | 'website';

/** Broad media type derived from source + URL structure. */
export type MediaType = 'video' | 'audio' | 'image' | 'article' | 'product' | 'social_post' | 'web';

/** High-level content category generated by AI. */
export type ContentCategory =
  | 'Finance'
  | 'Technology'
  | 'Health'
  | 'Travel'
  | 'Food'
  | 'Career'
  | 'Learning'
  | 'Entertainment'
  | 'Science'
  | 'Sports'
  | 'Politics'
  | 'Design'
  | 'Business'
  | 'Lifestyle'
  | 'Real Estate'
  | 'Other';

/** Extracted location data from page content. */
export interface ContentLocation {
  venue?: string;
  city?: string;
  country?: string;
  coordinates?: { lat: number; lng: number };
}

export type AIProvider =
  | 'openai'
  | 'anthropic'
  | 'watsonx'
  | 'gemini'
  | 'deepseek'
  | 'groq'
  | 'indus'
  | 'local';

/**
 * Which local inference back-end to use when provider === 'local'.
 *  - 'ollama'   : Ollama REST API  (default http://localhost:11434/v1)
 *  - 'lmstudio' : LM Studio REST   (default http://localhost:1234/v1)
 *  - 'llamacpp' : llama.cpp server / any OpenAI-compatible endpoint
 *  - 'gguf'     : Direct GGUF file path (future native bridge; routed via
 *                 a local llama.cpp-compatible server for now)
 */
export type LocalAISource = 'ollama' | 'lmstudio' | 'llamacpp' | 'openai-compatible' | 'gguf';

export interface SavedItem {
  /** UUID v4 */
  id: string;
  /** Max 200 characters */
  title: string;
  /** Max 2000 characters */
  description?: string;
  /** Validated http(s) URL, max 2048 characters */
  url?: string;
  /** Thumbnail URL (OG image / Twitter card / YouTube thumbnail) */
  imageUrl?: string;
  contentType: ContentType;
  collectionId?: string;
  /** Array of lowercase tags, each max 50 chars, max 20 tags */
  tags: string[];
  /** Max 5000 characters */
  notes?: string;
  /** Place name / address text from saved content, max 300 chars */
  address?: string;
  /** GPS latitude (optional, from expo-location) */
  latitude?: number;
  /** GPS longitude (optional, from expo-location) */
  longitude?: number;
  isCompleted: boolean;
  isFavorite: boolean;
  aiSummary?: string;
  /** Detected source platform (instagram, youtube, etc.) */
  source?: UrlSource;
  /** Broad media type detected from source + page */
  mediaType?: MediaType;
  /** AI-generated primary category */
  category?: ContentCategory;
  /** Up to 3 collection IDs suggested by AI (not auto-assigned) */
  suggestedCollections?: string[];
  /** Primary language detected in the content (title + description + summary) */
  detectedLanguage?: string;
  /** AI-translated summary (when autoTranslate is on and content is foreign) */
  translatedSummary?: string;
  /** AI-translated tags (when autoTranslate is on and content is foreign) */
  translatedTags?: string[];
  /** One-sentence reason the AI chose the category */
  categoryReason?: string;
  /** One-sentence reason the AI suggested the collections */
  collectionReason?: string;
  /** ID of the Topic this item is filed under (Level 2) */
  topicId?: string;
  /** Normalized topic label suggested by AI (e.g. "machine learning") */
  topicSuggestion?: string;
  /** Original topic text returned by AI before normalization */
  topicSuggestionRaw?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Topic {
  id: string;
  label: string;
  normalizedLabel: string;
  parentCollectionId: string;
  itemCount: number;
  createdAt: string;
}

export interface Collection {
  id: string;
  name: string;
  description?: string;
  /** Ionicons icon name */
  icon: IconName;
  color: string;
  isSystem: boolean;
  /** Cached item count from the database JOIN */
  itemCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface AISettings {
  provider: AIProvider;
  apiKey: string;
  model?: string;
  // IBM watsonx extras
  watsonxProjectId?: string;
  watsonxRegion?: string;
  // Local LLM (Ollama / LM Studio / llama.cpp / GGUF)
  localBaseUrl?: string;
  /** Which local back-end to use; only relevant when provider === 'local' */
  localSource?: LocalAISource;
  /** Absolute path to a .gguf model file selected by the user */
  localGgufPath?: string;
  /** File size in bytes of the selected .gguf model */
  localGgufSize?: number;
  /** Display name of the selected .gguf model file */
  localGgufName?: string;
  /** Whether local AI mode is enabled */
  localEnabled?: boolean;
  /** Context window size in tokens (local inference) */
  localContextLength?: number;
}

// ─── AI Health Monitoring ──────────────────────────────────────────────────

export type AIConnectionStatus = 'connected' | 'limited' | 'offline' | 'unknown';

export interface AIQuotaInfo {
  requestsRemaining?: number;
  tokensRemaining?:   number;
  dailyLimit?:        number;
  monthlyLimit?:      number;
}

export interface AIRateLimitInfo {
  /** Seconds until the rate limit resets */
  retryAfterSeconds: number;
  /** When this info was recorded */
  detectedAt: string;
}

export interface AIHealthStatus {
  /** The provider this status belongs to */
  provider: AIProvider;
  /** Derived connection status */
  status: AIConnectionStatus;
  /** ISO timestamp of the last successful check */
  lastSuccessfulCheck?: string;
  /** ISO timestamp of the last check attempt (successful or not) */
  lastCheckedAt?: string;
  /** Response time in ms from the last successful check */
  responseTimeMs?: number;
  /** Model reported by the endpoint (may differ from configured model) */
  confirmedModel?: string;
  /** Quota data if the provider exposes it */
  quota?: AIQuotaInfo;
  /** Active rate-limit window, present only when a 429 was received */
  rateLimit?: AIRateLimitInfo;
  /** Human-readable error message from the last failed check (never raw stack) */
  lastErrorMessage?: string;
}

export type AppearanceStyle = 'classic' | 'material-you' | 'expressive';

/** What happens after a successful share into Lumio. */
export type ShareBehavior = 'stay' | 'open_lumio';

export interface AppSettings {
  theme: 'light' | 'dark' | 'system';
  appearanceStyle?: AppearanceStyle;
  dynamicColors?: boolean;
  useThemedIcon?: boolean;
  amoledBlack?: boolean;
  edgeToEdge?: boolean;
  dynamicNavigationBar?: boolean;
  dynamicStatusBar?: boolean;
  reduceMotion?: boolean;
  compactLayout?: boolean;
  largeTouchTargets?: boolean;
  highContrast?: boolean;
  defaultCollection?: string;
  /** Controls what happens after an item is shared into Lumio. Default: 'stay'. */
  shareBehavior?: ShareBehavior;
  aiSettings?: AISettings;
  mapDefaultLat?: number;
  mapDefaultLng?: number;
  /** When true, the in-memory diagnostics log records pipeline events. */
  diagnosticsEnabled?: boolean;
  /**
   * Auto-assign rules: maps ContentCategory → collectionId.
   * When a rule exists for a category, enriched items in that category are
   * automatically assigned to the mapped collection without prompting.
   */
  autoAssignRules?: Record<string, string>;
  /**
   * When true, non-English content is automatically translated before
   * summary, tags, and category are generated.
   */
  autoTranslateForeignContent?: boolean;
  /**
   * Languages that should never be auto-translated (user-configured list).
   * Values match DetectedLanguage strings (e.g. "Japanese", "French").
   */
  neverTranslateLanguages?: string[];
}

export type SortOption = 'newest' | 'oldest' | 'alphabetical' | 'type';
export type FilterOption = ContentType | 'all' | 'favorites' | 'completed';
