import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Alert,
  TextInput,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter, useNavigation } from 'expo-router';
import { ActivityIndicator as PaperActivityIndicator } from 'react-native-paper';
import { Ionicons } from '@expo/vector-icons';
import dayjs from 'dayjs';
import { useTheme } from '../../src/context/ThemeContext';
import { useAppTheme } from '../../src/constants/colors';
import { useData } from '../../src/context/DataContext';
import { getItemById, deleteItem, toggleFavorite, toggleCompleted, updateItem } from '../../src/database/items';
import { CONTENT_TYPE_CONFIG } from '../../src/constants';
import { getExactSourceLabel, CATEGORY_CONFIG } from '../../src/services/metadata';
import { logError, getUserMessage } from '../../src/utils/errors';
import type { SavedItem } from '../../src/types';

export default function ItemDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { colors } = useTheme();
  const paper = useAppTheme();
  const insets = useSafeAreaInsets();
  const { collections, refreshAll } = useData();
  const router = useRouter();
  const navigation = useNavigation();
  const [item, setItem] = useState<SavedItem | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editNotes, setEditNotes] = useState('');
  const [origDescExpanded, setOrigDescExpanded] = useState(false);
  const [assigningCollection, setAssigningCollection] = useState<string | null>(null);

  const loadItem = async () => {
    if (!id) return;
    const fetched = await getItemById(id);
    setItem(fetched);
    setEditNotes(fetched?.notes ?? '');
  };

  useEffect(() => {
    loadItem();
  }, [id]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!item) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
        <View style={styles.loading}>
          <PaperActivityIndicator size="large" color={paper.colors.primary} />
        </View>
      </SafeAreaView>
    );
  }

  const config = CONTENT_TYPE_CONFIG[item.contentType];
  const collection = collections.find((c) => c.id === item.collectionId);
  const exactSource = getExactSourceLabel(item.source, item.mediaType, item.url);
  const catConfig = item.category ? CATEGORY_CONFIG[item.category] : undefined;

  // AI Summary display logic:
  //   1. Use aiSummary if present (generated by enrichment pipeline).
  //   2. Fall back to description (raw page metadata) if AI was unavailable.
  //   3. Show "still enriching" hint if neither is available.
  const summaryText = item.aiSummary ?? item.description ?? null;
  const summaryIsAI = !!item.aiSummary;
  // Show "Original Description" collapsible only when we have both the AI
  // summary and the raw metadata description (and they differ).
  const showOrigDesc = !!item.aiSummary && !!item.description && item.aiSummary !== item.description;

  const handleSelectSuggestedCollection = async (targetCollectionId: string) => {
    if (assigningCollection) return; // prevent double-tap
    const isCurrent = item.collectionId === targetCollectionId;
    const newCollectionId = isCurrent ? undefined : targetCollectionId;

    // Optimistic update — reflect the change in local state immediately
    setItem((prev) => prev ? { ...prev, collectionId: newCollectionId } : prev);
    setAssigningCollection(targetCollectionId);

    try {
      await updateItem(item.id, { collectionId: newCollectionId });
      // Reload item from DB to confirm, then refresh global context (updates counts)
      await loadItem();
      await refreshAll();
    } catch (err) {
      // Roll back optimistic update on failure
      await loadItem();
      logError(err, { screen: 'item', action: 'assignCollection' });
      Alert.alert('Error', getUserMessage(err));
    } finally {
      setAssigningCollection(null);
    }
  };

  const handleDelete = () => {
    Alert.alert('Delete Item', `Remove "${item.title}"?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          try {
            await deleteItem(item.id);
            await refreshAll();
            router.back();
          } catch (err) {
            logError(err, { screen: 'item', action: 'delete' });
            Alert.alert('Error', getUserMessage(err));
          }
        },
      },
    ]);
  };

  const handleFavorite = async () => {
    await toggleFavorite(item.id, item.isFavorite);
    await loadItem();
    await refreshAll();
  };

  const handleComplete = async () => {
    await toggleCompleted(item.id, item.isCompleted);
    await loadItem();
    await refreshAll();
  };

  const handleSaveNotes = async () => {
    await updateItem(item.id, { notes: editNotes.trim() || undefined });
    await loadItem();
    setIsEditing(false);
  };

  const handleOpenUrl = () => {
    if (item.url) Linking.openURL(item.url);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      {/* ── Navigation Bar ── */}
      <View style={[styles.navBar, { borderBottomColor: colors.border }]}>
        <TouchableOpacity
          onPress={() => {
            if (navigation.canGoBack()) {
              router.back();
            } else {
              router.replace('/(tabs)');
            }
          }}
          style={styles.backBtn}
        >
          <Ionicons name="chevron-back" size={20} color={paper.colors.primary} />
          <Text style={{ color: paper.colors.primary, fontSize: 16 }}>Back</Text>
        </TouchableOpacity>
        <View style={styles.navActions}>
          <TouchableOpacity onPress={handleFavorite} accessibilityRole="button" accessibilityLabel={item.isFavorite ? 'Remove from favorites' : 'Add to favorites'}>
            <Ionicons
              name={item.isFavorite ? 'heart' : 'heart-outline'}
              size={22}
              color={item.isFavorite ? paper.colors.error : paper.colors.onSurfaceVariant}
            />
          </TouchableOpacity>
          <TouchableOpacity onPress={handleDelete} accessibilityRole="button" accessibilityLabel="Delete item">
            <Ionicons name="trash-outline" size={22} color={paper.colors.error} />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 24 }]}>

        {/* ── 1. Source + Category badges ── */}
        <View style={styles.badgesRow}>
          <View style={[styles.typeBadge, { backgroundColor: config.color + '20' }]}>
            <Ionicons name={config.icon as React.ComponentProps<typeof Ionicons>['name']} size={14} color={config.color} />
            <Text style={[styles.typeLabel, { color: config.color }]}>{exactSource}</Text>
          </View>
          {item.category && (
            <View
              style={[
                styles.typeBadge,
                {
                  backgroundColor: (catConfig?.color ?? '#10b981') + '20',
                  borderColor: (catConfig?.color ?? '#10b981') + '40',
                  borderWidth: 1,
                },
              ]}
            >
              <Text style={[styles.typeLabel, { color: catConfig?.color ?? colors.text, fontWeight: '700' }]}>
                {`${catConfig?.emoji ?? '🏷️'} ${item.category}`}
              </Text>
            </View>
          )}
        </View>

        {/* ── 2. Title ── */}
        <Text style={[styles.title, { color: colors.text }]}>{item.title}</Text>

        {/* ── 3. Meta row: date + current collection ── */}
        <View style={styles.metaRow}>
          <Text style={[styles.meta, { color: colors.textMuted }]}>
            {dayjs(item.createdAt).format('MMM D, YYYY')}
          </Text>
          {collection && (
            <View style={[styles.collectionChip, { backgroundColor: collection.color + '20', borderColor: collection.color + '40', borderWidth: 1 }]}>
              <Ionicons name={collection.icon as React.ComponentProps<typeof Ionicons>['name']} size={11} color={collection.color} />
              <Text style={[styles.collectionChipText, { color: collection.color }]}>
                {collection.name}
              </Text>
            </View>
          )}
        </View>

        {/* ── 4. URL ── */}
        {item.url && (
          <TouchableOpacity
            onPress={handleOpenUrl}
            style={[styles.urlRow, { backgroundColor: paper.colors.surfaceContainerHigh, borderColor: paper.colors.outlineVariant }]}
            accessibilityRole="link"
            accessibilityLabel="Open URL"
          >
            <Ionicons name="link" size={15} color={paper.colors.primary} />
            <Text style={[styles.urlText, { color: paper.colors.primary }]} numberOfLines={1}>
              {item.url}
            </Text>
            <Ionicons name="open-outline" size={15} color={paper.colors.primary} />
          </TouchableOpacity>
        )}

        {/* ── 5. AI Summary ─────────────────────────────────────────────────────
            Primary content section. Shows:
              • AI-generated summary (from enrichment pipeline), or
              • Raw metadata description as fallback when AI was unavailable, or
              • "Still enriching" hint if neither is available yet.              */}
        <View style={[styles.section, { backgroundColor: paper.colors.tertiaryContainer + '30', borderColor: paper.colors.tertiary + '40' }]}>
          <View style={styles.sectionHeader}>
            <View style={styles.sectionTitleRow}>
              <Ionicons name="sparkles" size={14} color={paper.colors.tertiary} />
              <View>
                <Text style={[styles.sectionTitle, { color: paper.colors.tertiary }]}>AI SUMMARY</Text>
                {!summaryIsAI && summaryText && (
                  <Text style={{ fontSize: 10, color: paper.colors.tertiary + '99', fontWeight: '500', marginTop: 1 }}>
                    From source metadata
                  </Text>
                )}
                {summaryIsAI && (
                  <Text style={{ fontSize: 10, color: paper.colors.tertiary + '99', fontWeight: '500', marginTop: 1 }}>
                    Generated by Lumio AI
                  </Text>
                )}
              </View>
            </View>
          </View>
          {summaryText ? (
            <Text style={[styles.bodyText, { color: colors.text }]}>{summaryText}</Text>
          ) : (
            <Text style={[styles.bodyText, { color: colors.textMuted }]}>
              Enrichment in progress — AI summary will appear here shortly.
            </Text>
          )}
        </View>

        {/* ── 6. Original Description — collapsible ────────────────────────────
            Only shown when an AI summary exists AND the raw metadata description
            is different (so it's not duplicating the summary). Collapsed by default. */}
        {showOrigDesc && (
          <TouchableOpacity
            onPress={() => setOrigDescExpanded((v) => !v)}
            activeOpacity={0.8}
            style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}
            accessibilityRole="button"
            accessibilityLabel={origDescExpanded ? 'Collapse original description' : 'Expand original description'}
          >
            <View style={[styles.sectionHeader, { marginBottom: origDescExpanded ? 8 : 0 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="document-text-outline" size={14} color={colors.textMuted} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>ORIGINAL DESCRIPTION</Text>
              </View>
              <Ionicons
                name={origDescExpanded ? 'chevron-up' : 'chevron-down'}
                size={15}
                color={colors.textMuted}
              />
            </View>
            {origDescExpanded && (
              <Text style={[styles.bodyText, { color: colors.text }]}>{item.description}</Text>
            )}
          </TouchableOpacity>
        )}

        {/* ── 7. Suggested Collections ── */}
        {item.suggestedCollections && item.suggestedCollections.length > 0 && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={[styles.sectionHeader, { marginBottom: 4 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="folder-outline" size={14} color={paper.colors.primary} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>SUGGESTED COLLECTIONS</Text>
              </View>
              {assigningCollection && (
                <PaperActivityIndicator size={14} color={paper.colors.primary} />
              )}
            </View>

            {/* Current assignment row */}
            {item.collectionId && collection && (
              <View style={[styles.currentCollectionRow, { backgroundColor: collection.color + '15', borderColor: collection.color + '40' }]}>
                <Ionicons name="checkmark-circle" size={15} color={collection.color} />
                <Text style={[styles.currentCollectionLabel, { color: colors.textMuted }]}>Current:</Text>
                <Ionicons name={collection.icon as React.ComponentProps<typeof Ionicons>['name']} size={13} color={collection.color} />
                <Text style={[styles.currentCollectionName, { color: collection.color }]}>{collection.name}</Text>
              </View>
            )}

            <Text style={[styles.hint, { color: colors.textMuted, marginBottom: 8, marginTop: item.collectionId ? 8 : 2 }]}>
              {item.collectionId ? 'Tap to reassign or remove:' : 'Tap to assign this item:'}
            </Text>

            <View style={styles.suggestedCollectionsRow}>
              {item.suggestedCollections.map((cid) => {
                const col = collections.find((c) => c.id === cid);
                if (!col) return null;
                const isSelected = item.collectionId === cid;
                const isAssigning = assigningCollection === cid;
                return (
                  <TouchableOpacity
                    key={cid}
                    onPress={() => handleSelectSuggestedCollection(cid)}
                    disabled={!!assigningCollection}
                    accessibilityRole="button"
                    accessibilityLabel={isSelected ? `Remove from ${col.name}` : `Assign to ${col.name}`}
                    style={[
                      styles.suggestedColChip,
                      {
                        backgroundColor: isSelected ? col.color : paper.colors.surfaceContainerHighest,
                        borderColor: isSelected ? col.color : paper.colors.secondary + '66',
                        borderStyle: isSelected ? 'solid' : 'dashed',
                        opacity: assigningCollection && !isAssigning ? 0.5 : 1,
                      },
                    ]}
                  >
                    {isAssigning ? (
                      <PaperActivityIndicator size={13} color={isSelected ? '#fff' : paper.colors.secondary} />
                    ) : (
                      <Ionicons
                        name={isSelected ? 'checkmark' : 'sparkles'}
                        size={13}
                        color={isSelected ? '#fff' : paper.colors.secondary}
                      />
                    )}
                    <Ionicons
                      name={col.icon as React.ComponentProps<typeof Ionicons>['name']}
                      size={14}
                      color={isSelected ? '#fff' : paper.colors.onSurfaceVariant}
                    />
                    <Text style={{ fontSize: 13, fontWeight: '600', color: isSelected ? '#fff' : paper.colors.onSurfaceVariant }}>
                      {col.name}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>
        )}

        {/* ── 8. Tags ── */}
        {item.tags.length > 0 && (
          <View style={styles.tagsSection}>
            <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>TAGS</Text>
            <View style={styles.tagsRow}>
              {item.tags.map((tag) => (
                <View key={tag} style={[styles.tag, { backgroundColor: colors.surfaceContainerHigh }]}>
                  <Text style={[styles.tagText, { color: colors.textSecondary }]}>#{tag}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* ── 9. Location ── */}
        {(item.address || (item.latitude && item.longitude)) && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={styles.sectionTitleRow}>
              <Ionicons name="location" size={14} color={paper.colors.primary} />
              <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>LOCATION</Text>
            </View>
            {item.address && (
              <Text style={[styles.bodyText, { color: colors.text }]}>{item.address}</Text>
            )}
            {item.latitude && item.longitude && (
              <Text style={[styles.meta, { color: colors.textMuted, marginTop: 2, fontFamily: 'monospace' }]}>
                {`${item.latitude.toFixed(6)}, ${item.longitude.toFixed(6)}`}
              </Text>
            )}
            <TouchableOpacity
              onPress={() => {
                let mapsUrl: string;
                let fallback: string;
                if (item.latitude && item.longitude) {
                  mapsUrl = `geo:${item.latitude},${item.longitude}?q=${item.latitude},${item.longitude}`;
                  fallback = `https://maps.google.com/?q=${item.latitude},${item.longitude}`;
                } else {
                  const encoded = encodeURIComponent(item.address ?? '');
                  mapsUrl = `geo:0,0?q=${encoded}`;
                  fallback = `https://maps.google.com/?q=${encoded}`;
                }
                Linking.canOpenURL(mapsUrl)
                  .then((ok) => Linking.openURL(ok ? mapsUrl : fallback))
                  .catch(() => Linking.openURL(fallback));
              }}
              style={[styles.openMapsBtn, { backgroundColor: paper.colors.primaryContainer }]}
              accessibilityRole="button"
              accessibilityLabel="Open in Google Maps"
            >
              <Ionicons name="navigate" size={16} color={paper.colors.onPrimaryContainer} />
              <Text style={[styles.openMapsBtnText, { color: paper.colors.onPrimaryContainer }]}>Open in Google Maps</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* ── 10. Notes (editable) ── */}
        <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
          <View style={styles.sectionHeader}>
            <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>MY NOTES</Text>
            <TouchableOpacity onPress={() => (isEditing ? handleSaveNotes() : setIsEditing(true))}>
              <Text style={{ color: paper.colors.primary, fontSize: 13, fontWeight: '600' }}>
                {isEditing ? 'Save' : 'Edit'}
              </Text>
            </TouchableOpacity>
          </View>
          {isEditing ? (
            <TextInput
              value={editNotes}
              onChangeText={setEditNotes}
              multiline
              placeholder="Add your notes here…"
              placeholderTextColor={colors.placeholder}
              style={[styles.notesInput, { color: colors.text, borderColor: colors.border }]}
              autoFocus
              textAlignVertical="top"
            />
          ) : (
            <Text style={[styles.bodyText, { color: item.notes ? colors.text : colors.textMuted }]}>
              {item.notes ?? 'No notes yet. Tap Edit to add.'}
            </Text>
          )}
        </View>

        {/* ── 11. Actions ── */}
        <View style={styles.actionButtons}>
          <TouchableOpacity
            onPress={handleComplete}
            style={[
              styles.actionBtn,
              {
                backgroundColor: item.isCompleted ? colors.success + '20' : colors.surfaceContainerHigh,
                borderColor: item.isCompleted ? colors.success : colors.border,
              },
            ]}
            accessibilityRole="button"
            accessibilityLabel={item.isCompleted ? 'Mark as not done' : 'Mark as done'}
          >
            <Ionicons
              name={item.isCompleted ? 'checkmark-circle' : 'checkmark-circle-outline'}
              size={20}
              color={item.isCompleted ? colors.success : colors.textSecondary}
            />
            <Text style={[styles.actionBtnText, { color: item.isCompleted ? colors.success : colors.textSecondary }]}>
              {item.isCompleted ? 'Completed!' : 'Mark as Done'}
            </Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  navActions: { flexDirection: 'row', gap: 18 },
  content: { paddingHorizontal: 16, paddingTop: 16, gap: 12 },
  badgesRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 5,
  },
  typeLabel: { fontSize: 12, fontWeight: '700' },
  title: { fontSize: 22, fontWeight: '800', lineHeight: 28, marginTop: 4 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  meta: { fontSize: 13 },
  collectionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  collectionChipText: { fontSize: 12, fontWeight: '600' },
  urlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  urlText: { flex: 1, fontSize: 13, fontWeight: '500' },
  section: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionTitle: { fontSize: 11, fontWeight: '700', letterSpacing: 0.8 },
  bodyText: { fontSize: 15, lineHeight: 22 },
  hint: { fontSize: 12, lineHeight: 17 },
  notesInput: {
    fontSize: 15,
    lineHeight: 22,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    minHeight: 80,
  },
  tagsSection: { gap: 8 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  tagText: { fontSize: 13, fontWeight: '500' },
  currentCollectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
  },
  currentCollectionLabel: { fontSize: 12, fontWeight: '600' },
  currentCollectionName: { fontSize: 13, fontWeight: '700', flex: 1 },
  suggestedCollectionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  suggestedColChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1.5,
    gap: 5,
  },
  openMapsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 6,
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  openMapsBtnText: { fontSize: 13, fontWeight: '600' },
  actionButtons: { gap: 10 },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  actionBtnText: { fontSize: 14, fontWeight: '600' },
});
