import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Alert,
  TextInput,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter, useNavigation } from 'expo-router';
import { ActivityIndicator as PaperActivityIndicator } from 'react-native-paper';
import { Ionicons } from '@expo/vector-icons';
import dayjs from 'dayjs';
import { useTheme } from '../../src/context/ThemeContext';
import { useAppTheme } from '../../src/constants/colors';
import { useData } from '../../src/context/DataContext';
import { useCaptureQueue } from '../../src/context/CaptureQueueContext';
import { getItemById, deleteItem, toggleFavorite, toggleCompleted, updateItem } from '../../src/database/items';
import { CONTENT_TYPE_CONFIG } from '../../src/constants';
import { getExactSourceLabel, CATEGORY_CONFIG } from '../../src/services/metadata';
import { findRelatedItems, type RelatedItemMatch } from '../../src/services/collectionInsights';
import { logError, getUserMessage } from '../../src/utils/errors';
import type { SavedItem } from '../../src/types';

export default function ItemDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { colors } = useTheme();
  const paper = useAppTheme();
  const insets = useSafeAreaInsets();
  const { collections, items: allItems, refreshAll } = useData();
  const { queue } = useCaptureQueue();
  const router = useRouter();
  const navigation = useNavigation();
  const [item, setItem] = useState<SavedItem | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editNotes, setEditNotes] = useState('');
  const [origDescExpanded, setOrigDescExpanded] = useState(false);
  const [origLangExpanded, setOrigLangExpanded] = useState(false);
  const [assigningCollection, setAssigningCollection] = useState<string | null>(null);
  const [categoryReasonExpanded, setCategoryReasonExpanded] = useState(false);

  const loadItem = async () => {
    if (!id) return;
    const fetched = await getItemById(id);
    setItem(fetched);
    setEditNotes(fetched?.notes ?? '');
  };

  // Initial load
  useEffect(() => {
    loadItem();
  }, [id]); // eslint-disable-line -- loadItem is stable; id is the only meaningful dep

  // Re-load item whenever the capture queue marks THIS item's enrichment as
  // completed or failed.  Without this the detail screen shows the skeleton
  // title/summary that was written at enqueue time and never updates.
  const prevQueueRef = useRef(queue);
  useEffect(() => {
    if (!id) return;
    const prev = prevQueueRef.current;
    prevQueueRef.current = queue;
    const wasActive = prev.some(
      (e) => e.itemId === id && (e.status === 'queued' || e.status === 'processing')
    );
    const isNowDone = queue.some(
      (e) => e.itemId === id && (e.status === 'completed' || e.status === 'failed')
    );
    if (wasActive && isNowDone) {
      loadItem();
    }
  // Intentionally no dependency array — this effect must run on every render
  // so it can compare the previous vs current queue snapshot and detect when
  // THIS item's enrichment transitions from active → completed/failed.
  }); // eslint-disable-line

  if (!item) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
        <View style={styles.loading}>
          <PaperActivityIndicator size="large" color={paper.colors.primary} />
        </View>
      </SafeAreaView>
    );
  }

  const config = CONTENT_TYPE_CONFIG[item.contentType];
  const collection = collections.find((c) => c.id === item.collectionId);
  const exactSource = getExactSourceLabel(item.source, item.mediaType, item.url);
  const catConfig = item.category ? CATEGORY_CONFIG[item.category] : undefined;

  // AI Summary display logic:
  //   1. Use translatedSummary if available and the item has a foreign language.
  //   2. Use aiSummary if present (generated by enrichment pipeline).
  //   3. Fall back to description (raw page metadata) if AI was unavailable.
  //   4. Show "still enriching" hint if neither is available.
  const hasTranslation = !!(item.translatedSummary && item.detectedLanguage && item.detectedLanguage !== 'English');
  const summaryText = (hasTranslation ? item.translatedSummary : null) ?? item.aiSummary ?? item.description ?? null;
  const summaryIsAI = !!item.aiSummary || !!item.translatedSummary;
  // Show "Original Description" collapsible only when we have both the AI
  // summary and the raw metadata description (and they differ).
  const showOrigDesc = !!item.aiSummary && !!item.description && item.aiSummary !== item.description;
  // Display tags: prefer translated tags when available
  const displayTags = (hasTranslation && item.translatedTags && item.translatedTags.length > 0)
    ? item.translatedTags
    : item.tags;

  const relatedItems = findRelatedItems(item, allItems);

  const handleSelectSuggestedCollection = async (targetCollectionId: string) => {
    if (assigningCollection) return; // prevent double-tap
    const isCurrent = item.collectionId === targetCollectionId;
    const newCollectionId = isCurrent ? undefined : targetCollectionId;

    // Optimistic update — reflect the change in local state immediately
    setItem((prev) => prev ? { ...prev, collectionId: newCollectionId } : prev);
    setAssigningCollection(targetCollectionId);

    try {
      await updateItem(item.id, { collectionId: newCollectionId });
      // Reload item from DB to confirm, then refresh global context (updates counts)
      await loadItem();
      await refreshAll();
    } catch (err) {
      // Roll back optimistic update on failure
      await loadItem();
      logError(err, { screen: 'item', action: 'assignCollection' });
      Alert.alert('Error', getUserMessage(err));
    } finally {
      setAssigningCollection(null);
    }
  };

  const handleDelete = () => {
    Alert.alert('Delete Item', `Remove "${item.title}"?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          try {
            await deleteItem(item.id);
            await refreshAll();
            router.back();
          } catch (err) {
            logError(err, { screen: 'item', action: 'delete' });
            Alert.alert('Error', getUserMessage(err));
          }
        },
      },
    ]);
  };

  const handleFavorite = async () => {
    await toggleFavorite(item.id, item.isFavorite);
    await loadItem();
    await refreshAll();
  };

  const handleComplete = async () => {
    await toggleCompleted(item.id, item.isCompleted);
    await loadItem();
    await refreshAll();
  };

  const handleSaveNotes = async () => {
    await updateItem(item.id, { notes: editNotes.trim() || undefined });
    await loadItem();
    setIsEditing(false);
  };

  const handleOpenUrl = () => {
    if (item.url) Linking.openURL(item.url);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      {/* ── Navigation Bar ── */}
      <View style={[styles.navBar, { borderBottomColor: colors.border }]}>
        <TouchableOpacity
          onPress={() => {
            if (navigation.canGoBack()) {
              router.back();
            } else {
              router.replace('/(tabs)');
            }
          }}
          style={styles.backBtn}
        >
          <Ionicons name="chevron-back" size={20} color={paper.colors.primary} />
          <Text style={{ color: paper.colors.primary, fontSize: 16 }}>Back</Text>
        </TouchableOpacity>
        <View style={styles.navActions}>
          <TouchableOpacity onPress={handleFavorite} accessibilityRole="button" accessibilityLabel={item.isFavorite ? 'Remove from favorites' : 'Add to favorites'}>
            <Ionicons
              name={item.isFavorite ? 'heart' : 'heart-outline'}
              size={22}
              color={item.isFavorite ? paper.colors.error : paper.colors.onSurfaceVariant}
            />
          </TouchableOpacity>
          <TouchableOpacity onPress={handleDelete} accessibilityRole="button" accessibilityLabel="Delete item">
            <Ionicons name="trash-outline" size={22} color={paper.colors.error} />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 24 }]}>

        {/* ── 1. Source + Category badges ── */}
        <View style={styles.badgesRow}>
          <View style={[styles.typeBadge, { backgroundColor: config.color + '20' }]}>
            <Ionicons name={config.icon as React.ComponentProps<typeof Ionicons>['name']} size={14} color={config.color} />
            <Text style={[styles.typeLabel, { color: config.color }]}>{exactSource}</Text>
          </View>
          {item.category && (
            <TouchableOpacity
              onPress={() => item.categoryReason ? setCategoryReasonExpanded((v) => !v) : undefined}
              activeOpacity={item.categoryReason ? 0.7 : 1}
              style={[
                styles.typeBadge,
                {
                  backgroundColor: (catConfig?.color ?? '#10b981') + '20',
                  borderColor: (catConfig?.color ?? '#10b981') + '40',
                  borderWidth: 1,
                },
              ]}
              accessibilityRole={item.categoryReason ? 'button' : 'text'}
              accessibilityLabel={item.categoryReason ? `Category: ${item.category}. Tap for reason.` : `Category: ${item.category}`}
            >
              <Text style={[styles.typeLabel, { color: catConfig?.color ?? colors.text, fontWeight: '700' }]}>
                {`${catConfig?.emoji ?? '🏷️'} ${item.category}`}
              </Text>
              {item.categoryReason && (
                <Ionicons name={categoryReasonExpanded ? 'chevron-up' : 'information-circle-outline'} size={12} color={catConfig?.color ?? colors.text} />
              )}
            </TouchableOpacity>
          )}
          {/* Category reason inline — shown when badge is tapped */}
          {item.categoryReason && categoryReasonExpanded && (
            <View style={[styles.reasonBubble, { backgroundColor: (catConfig?.color ?? '#10b981') + '15', borderColor: (catConfig?.color ?? '#10b981') + '30' }]}>
              <Ionicons name="bulb-outline" size={12} color={catConfig?.color ?? colors.textMuted} />
              <Text style={[styles.reasonText, { color: catConfig?.color ?? colors.textMuted }]}>{item.categoryReason}</Text>
            </View>
          )}
          {/* Language badge — shown whenever a non-English language is detected */}
          {item.detectedLanguage && item.detectedLanguage !== 'English' && item.detectedLanguage !== 'Unknown' && (
            <View style={[styles.typeBadge, { backgroundColor: paper.colors.tertiaryContainer, borderColor: paper.colors.tertiary + '50', borderWidth: 1 }]}>
              <Ionicons name="language" size={12} color={paper.colors.onTertiaryContainer} />
              <Text style={[styles.typeLabel, { color: paper.colors.onTertiaryContainer }]}>{item.detectedLanguage}</Text>
              {hasTranslation && (
                <Ionicons name="checkmark-circle" size={11} color={paper.colors.onTertiaryContainer} />
              )}
            </View>
          )}
        </View>

        {/* ── 2. Title ── */}
        <Text style={[styles.title, { color: colors.text }]}>{item.title}</Text>

        {/* ── 3. Meta row: date + current collection ── */}
        <View style={styles.metaRow}>
          <Text style={[styles.meta, { color: colors.textMuted }]}>
            {dayjs(item.createdAt).format('MMM D, YYYY')}
          </Text>
          {collection && (
            <View style={[styles.collectionChip, { backgroundColor: collection.color + '20', borderColor: collection.color + '40', borderWidth: 1 }]}>
              <Ionicons name={collection.icon as React.ComponentProps<typeof Ionicons>['name']} size={11} color={collection.color} />
              <Text style={[styles.collectionChipText, { color: collection.color }]}>
                {collection.name}
              </Text>
            </View>
          )}
        </View>

        {/* ── 4. URL ── */}
        {item.url && (
          <TouchableOpacity
            onPress={handleOpenUrl}
            style={[styles.urlRow, { backgroundColor: paper.colors.surfaceContainerHigh, borderColor: paper.colors.outlineVariant }]}
            accessibilityRole="link"
            accessibilityLabel="Open URL"
          >
            <Ionicons name="link" size={15} color={paper.colors.primary} />
            <Text style={[styles.urlText, { color: paper.colors.primary }]} numberOfLines={1}>
              {item.url}
            </Text>
            <Ionicons name="open-outline" size={15} color={paper.colors.primary} />
          </TouchableOpacity>
        )}

        {/* ── 5. AI Summary ─────────────────────────────────────────────────────
            Primary content section. Shows:
              • AI-generated / translated summary (primary), or
              • Raw metadata description as fallback when AI was unavailable, or
              • "Still enriching" hint if neither is available yet.              */}
        <View style={[styles.section, { backgroundColor: paper.colors.tertiaryContainer + '30', borderColor: paper.colors.tertiary + '40' }]}>
          <View style={styles.sectionHeader}>
            <View style={styles.sectionTitleRow}>
              <Ionicons name="sparkles" size={14} color={paper.colors.tertiary} />
              <View>
                <Text style={[styles.sectionTitle, { color: paper.colors.tertiary }]}>AI SUMMARY</Text>
                <Text style={{ fontSize: 10, color: paper.colors.tertiary + '99', fontWeight: '500', marginTop: 1 }}>
                  {summaryIsAI ? 'Generated by Lumio AI' : summaryText ? 'From source metadata' : ''}
                </Text>
              </View>
            </View>
          </View>
          {summaryText ? (
            <Text style={[styles.bodyText, { color: colors.text }]}>{summaryText}</Text>
          ) : (
            <Text style={[styles.bodyText, { color: colors.textMuted }]}>
              Enrichment in progress — AI summary will appear here shortly.
            </Text>
          )}
        </View>

        {/* ── 5b. Translation banner — shown when non-English content was translated ── */}
        {item.detectedLanguage && item.detectedLanguage !== 'Unknown' && item.detectedLanguage !== 'English' && (
          <View style={[styles.translationBanner, { backgroundColor: paper.colors.tertiaryContainer + '50', borderColor: paper.colors.tertiary + '40' }]}>
            {/* Language info row */}
            <View style={styles.translationRow}>
              <View style={styles.translationItem}>
                <Ionicons name="globe-outline" size={14} color={paper.colors.tertiary} />
                <View>
                  <Text style={[styles.translationLabel, { color: paper.colors.tertiary + '99' }]}>Original Language</Text>
                  <Text style={[styles.translationValue, { color: paper.colors.onTertiaryContainer }]}>{item.detectedLanguage}</Text>
                </View>
              </View>
              {hasTranslation && (
                <>
                  <View style={[styles.translationDivider, { backgroundColor: paper.colors.tertiary + '30' }]} />
                  <View style={styles.translationItem}>
                    <Ionicons name="checkmark-circle" size={14} color={paper.colors.tertiary} />
                    <View>
                      <Text style={[styles.translationLabel, { color: paper.colors.tertiary + '99' }]}>Displayed In</Text>
                      <Text style={[styles.translationValue, { color: paper.colors.onTertiaryContainer }]}>English</Text>
                    </View>
                  </View>
                </>
              )}
            </View>

            {/* View Original collapsible — only when we have both the original and translated */}
            {hasTranslation && item.aiSummary && (
              <TouchableOpacity
                onPress={() => setOrigLangExpanded((v) => !v)}
                style={[styles.viewOriginalBtn, { borderTopColor: paper.colors.tertiary + '30' }]}
                accessibilityRole="button"
                accessibilityLabel={origLangExpanded ? 'Collapse original content' : 'View original content'}
                activeOpacity={0.7}
              >
                <Text style={[styles.viewOriginalText, { color: paper.colors.tertiary }]}>
                  {origLangExpanded ? 'Hide Original ▲' : 'View Original ▼'}
                </Text>
              </TouchableOpacity>
            )}
            {origLangExpanded && item.aiSummary && (
              <Text style={[styles.bodyText, { color: paper.colors.onTertiaryContainer, marginTop: 8 }]}>
                {item.aiSummary}
              </Text>
            )}
          </View>
        )}

        {/* ── 6. Original Content — collapsible ────────────────────────────────
            Only shown when an AI summary exists AND the raw metadata description
            is different (so it's not duplicating the summary). Collapsed by default. */}
        {showOrigDesc && (
          <TouchableOpacity
            onPress={() => setOrigDescExpanded((v) => !v)}
            activeOpacity={0.8}
            style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}
            accessibilityRole="button"
            accessibilityLabel={origDescExpanded ? 'Collapse original content' : 'Expand original content'}
          >
            <View style={[styles.sectionHeader, { marginBottom: origDescExpanded ? 8 : 0 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="document-text-outline" size={14} color={colors.textMuted} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>ORIGINAL CONTENT</Text>
              </View>
              <Ionicons
                name={origDescExpanded ? 'chevron-up' : 'chevron-down'}
                size={15}
                color={colors.textMuted}
              />
            </View>
            {origDescExpanded && (
              <Text style={[styles.bodyText, { color: colors.text }]}>{item.description}</Text>
            )}
          </TouchableOpacity>
        )}

        {/* ── 7. Suggested Collections ── */}
        {item.suggestedCollections && item.suggestedCollections.length > 0 && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={[styles.sectionHeader, { marginBottom: 4 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="folder-outline" size={14} color={paper.colors.primary} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>SUGGESTED COLLECTIONS</Text>
              </View>
              {assigningCollection && (
                <PaperActivityIndicator size={14} color={paper.colors.primary} />
              )}
            </View>

            {/* Current assignment row */}
            {item.collectionId && collection && (
              <View style={[styles.currentCollectionRow, { backgroundColor: collection.color + '15', borderColor: collection.color + '40' }]}>
                <Ionicons name="checkmark-circle" size={15} color={collection.color} />
                <Text style={[styles.currentCollectionLabel, { color: colors.textMuted }]}>Current:</Text>
                <Ionicons name={collection.icon as React.ComponentProps<typeof Ionicons>['name']} size={13} color={collection.color} />
                <Text style={[styles.currentCollectionName, { color: collection.color }]}>{collection.name}</Text>
              </View>
            )}

            {item.collectionReason && (
              <View style={[styles.reasonBubble, { backgroundColor: paper.colors.primaryContainer + '60', borderColor: paper.colors.primary + '30', marginBottom: 6, marginTop: 4 }]}>
                <Ionicons name="bulb-outline" size={12} color={paper.colors.primary} />
                <Text style={[styles.reasonText, { color: paper.colors.primary }]}>{item.collectionReason}</Text>
              </View>
            )}
            <Text style={[styles.hint, { color: colors.textMuted, marginBottom: 8, marginTop: item.collectionId ? 8 : 2 }]}>
              {item.collectionId ? 'Tap to reassign or remove:' : 'Tap to assign this item:'}
            </Text>

            <View style={styles.suggestedCollectionsRow}>
              {item.suggestedCollections.map((cid) => {
                const col = collections.find((c) => c.id === cid);
                if (!col) return null;
                const isSelected = item.collectionId === cid;
                const isAssigning = assigningCollection === cid;
                return (
                  <TouchableOpacity
                    key={cid}
                    onPress={() => handleSelectSuggestedCollection(cid)}
                    disabled={!!assigningCollection}
                    accessibilityRole="button"
                    accessibilityLabel={isSelected ? `Remove from ${col.name}` : `Assign to ${col.name}`}
                    style={[
                      styles.suggestedColChip,
                      {
                        backgroundColor: isSelected ? col.color : paper.colors.surfaceContainerHighest,
                        borderColor: isSelected ? col.color : paper.colors.secondary + '66',
                        borderStyle: isSelected ? 'solid' : 'dashed',
                        opacity: assigningCollection && !isAssigning ? 0.5 : 1,
                      },
                    ]}
                  >
                    {isAssigning ? (
                      <PaperActivityIndicator size={13} color={isSelected ? '#fff' : paper.colors.secondary} />
                    ) : (
                      <Ionicons
                        name={isSelected ? 'checkmark' : 'sparkles'}
                        size={13}
                        color={isSelected ? '#fff' : paper.colors.secondary}
                      />
                    )}
                    <Ionicons
                      name={col.icon as React.ComponentProps<typeof Ionicons>['name']}
                      size={14}
                      color={isSelected ? '#fff' : paper.colors.onSurfaceVariant}
                    />
                    <Text style={{ fontSize: 13, fontWeight: '600', color: isSelected ? '#fff' : paper.colors.onSurfaceVariant }}>
                      {col.name}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>
        )}

        {/* ── 8. Tags ── */}
        {displayTags.length > 0 && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={[styles.sectionHeader, { marginBottom: 4 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="pricetag-outline" size={14} color={paper.colors.secondary} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>
                  {hasTranslation ? 'TAGS (TRANSLATED)' : 'TAGS'}
                </Text>
              </View>
              {hasTranslation && item.tags.length > 0 && (
                <Text style={{ fontSize: 10, color: colors.textMuted }}>
                  {item.tags.slice(0, 3).map((t) => `#${t}`).join(' ')}
                </Text>
              )}
            </View>
            <View style={styles.tagsRow}>
              {displayTags.map((tag) => (
                <View key={tag} style={[styles.tag, { backgroundColor: paper.colors.secondaryContainer }]}>
                  <Text style={[styles.tagText, { color: paper.colors.onSecondaryContainer }]}>#{tag}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* ── 9. Location ── */}
        {(item.address || (item.latitude && item.longitude)) && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={styles.sectionTitleRow}>
              <Ionicons name="location" size={14} color={paper.colors.primary} />
              <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>LOCATION</Text>
            </View>
            {item.address && (
              <Text style={[styles.bodyText, { color: colors.text }]}>{item.address}</Text>
            )}
            {item.latitude && item.longitude && (
              <Text style={[styles.meta, { color: colors.textMuted, marginTop: 2, fontFamily: 'monospace' }]}>
                {`${item.latitude.toFixed(6)}, ${item.longitude.toFixed(6)}`}
              </Text>
            )}
            <TouchableOpacity
              onPress={() => {
                let mapsUrl: string;
                let fallback: string;
                if (item.latitude && item.longitude) {
                  mapsUrl = `geo:${item.latitude},${item.longitude}?q=${item.latitude},${item.longitude}`;
                  fallback = `https://maps.google.com/?q=${item.latitude},${item.longitude}`;
                } else {
                  const encoded = encodeURIComponent(item.address ?? '');
                  mapsUrl = `geo:0,0?q=${encoded}`;
                  fallback = `https://maps.google.com/?q=${encoded}`;
                }
                Linking.canOpenURL(mapsUrl)
                  .then((ok) => Linking.openURL(ok ? mapsUrl : fallback))
                  .catch(() => Linking.openURL(fallback));
              }}
              style={[styles.openMapsBtn, { backgroundColor: paper.colors.primaryContainer }]}
              accessibilityRole="button"
              accessibilityLabel="Open in Google Maps"
            >
              <Ionicons name="navigate" size={16} color={paper.colors.onPrimaryContainer} />
              <Text style={[styles.openMapsBtnText, { color: paper.colors.onPrimaryContainer }]}>Open in Google Maps</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* ── 10. Why Related? ── */}
        {relatedItems.length > 0 && (
          <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
            <View style={[styles.sectionHeader, { marginBottom: 4 }]}>
              <View style={styles.sectionTitleRow}>
                <Ionicons name="git-compare-outline" size={14} color={paper.colors.primary} />
                <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>WHY RELATED?</Text>
              </View>
            </View>
            {relatedItems.map((match: RelatedItemMatch) => {
              const catConfig2 = match.item.category ? CATEGORY_CONFIG[match.item.category] : undefined;
              return (
                <TouchableOpacity
                  key={match.item.id}
                  onPress={() => router.push(`/item/${match.item.id}`)}
                  style={[styles.relatedRow, { borderTopColor: colors.border }]}
                  accessibilityRole="button"
                  accessibilityLabel={`Open related item: ${match.item.title}`}
                >
                  <View style={{ flex: 1 }}>
                    <Text numberOfLines={1} style={[styles.relatedTitle, { color: colors.text }]}>{match.item.title}</Text>
                    {/* Reason chips */}
                    <View style={styles.relatedWhyRow}>
                      {match.categoryMatch && match.item.category && (
                        <View style={[styles.relatedReasonChip, { backgroundColor: (catConfig2?.color ?? paper.colors.primary) + '20', borderColor: (catConfig2?.color ?? paper.colors.primary) + '40' }]}>
                          <Text style={[styles.relatedReasonChipText, { color: catConfig2?.color ?? paper.colors.primary }]}>
                            {`${catConfig2?.emoji ?? '🏷️'} ${match.item.category}`}
                          </Text>
                        </View>
                      )}
                      {match.sharedTags.slice(0, 2).map((tag) => (
                        <View key={tag} style={[styles.relatedReasonChip, { backgroundColor: paper.colors.secondaryContainer, borderColor: paper.colors.secondary + '40' }]}>
                          <Text style={[styles.relatedReasonChipText, { color: paper.colors.onSecondaryContainer }]}>#{tag}</Text>
                        </View>
                      ))}
                    </View>
                  </View>
                  <Ionicons name="chevron-forward" size={16} color={colors.textMuted} />
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {/* ── 11. Notes (editable) ── */}
        <View style={[styles.section, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.border }]}>
          <View style={styles.sectionHeader}>
            <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>MY NOTES</Text>
            <TouchableOpacity onPress={() => (isEditing ? handleSaveNotes() : setIsEditing(true))}>
              <Text style={{ color: paper.colors.primary, fontSize: 13, fontWeight: '600' }}>
                {isEditing ? 'Save' : 'Edit'}
              </Text>
            </TouchableOpacity>
          </View>
          {isEditing ? (
            <TextInput
              value={editNotes}
              onChangeText={setEditNotes}
              multiline
              placeholder="Add your notes here…"
              placeholderTextColor={colors.placeholder}
              style={[styles.notesInput, { color: colors.text, borderColor: colors.border }]}
              autoFocus
              textAlignVertical="top"
            />
          ) : (
            <Text style={[styles.bodyText, { color: item.notes ? colors.text : colors.textMuted }]}>
              {item.notes ?? 'No notes yet. Tap Edit to add.'}
            </Text>
          )}
        </View>

        {/* ── 12. Actions ── */}
        <View style={styles.actionButtons}>
          <TouchableOpacity
            onPress={handleComplete}
            style={[
              styles.actionBtn,
              {
                backgroundColor: item.isCompleted ? colors.success + '20' : colors.surfaceContainerHigh,
                borderColor: item.isCompleted ? colors.success : colors.border,
              },
            ]}
            accessibilityRole="button"
            accessibilityLabel={item.isCompleted ? 'Mark as not done' : 'Mark as done'}
          >
            <Ionicons
              name={item.isCompleted ? 'checkmark-circle' : 'checkmark-circle-outline'}
              size={20}
              color={item.isCompleted ? colors.success : colors.textSecondary}
            />
            <Text style={[styles.actionBtnText, { color: item.isCompleted ? colors.success : colors.textSecondary }]}>
              {item.isCompleted ? 'Completed!' : 'Mark as Done'}
            </Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  navActions: { flexDirection: 'row', gap: 18 },
  content: { paddingHorizontal: 16, paddingTop: 16, gap: 12 },
  badgesRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 5,
  },
  typeLabel: { fontSize: 12, fontWeight: '700' },
  title: { fontSize: 22, fontWeight: '800', lineHeight: 28, marginTop: 4 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  meta: { fontSize: 13 },
  collectionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  collectionChipText: { fontSize: 12, fontWeight: '600' },
  urlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  urlText: { flex: 1, fontSize: 13, fontWeight: '500' },
  section: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionTitle: { fontSize: 11, fontWeight: '700', letterSpacing: 0.8 },
  bodyText: { fontSize: 15, lineHeight: 22 },
  hint: { fontSize: 12, lineHeight: 17 },
  notesInput: {
    fontSize: 15,
    lineHeight: 22,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    minHeight: 80,
  },
  tagsSection: { gap: 8 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  tagText: { fontSize: 13, fontWeight: '500' },
  currentCollectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
  },
  currentCollectionLabel: { fontSize: 12, fontWeight: '600' },
  currentCollectionName: { fontSize: 13, fontWeight: '700', flex: 1 },
  suggestedCollectionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  suggestedColChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1.5,
    gap: 5,
  },
  openMapsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 6,
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  openMapsBtnText: { fontSize: 13, fontWeight: '600' },
  relatedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 9,
    borderTopWidth: 1,
    marginTop: 7,
  },
  relatedTitle: { fontSize: 14, fontWeight: '600' },
  relatedWhyRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 5 },
  relatedReasonChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
  },
  relatedReasonChipText: { fontSize: 11, fontWeight: '600' },
  actionButtons: { gap: 10 },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  actionBtnText: { fontSize: 14, fontWeight: '600' },

  // AI reason bubbles (category / collection)
  reasonBubble: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
  },
  reasonText: { fontSize: 12, lineHeight: 17, flex: 1, fontStyle: 'italic' },

  // Translation banner (standalone card below AI Summary)
  translationBanner: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  translationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  translationItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  translationLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  translationValue: {
    fontSize: 13,
    fontWeight: '700',
  },
  translationDivider: {
    width: 1,
    height: 32,
    flexShrink: 0,
  },
  viewOriginalBtn: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
  },
  viewOriginalText: {
    fontSize: 13,
    fontWeight: '700',
  },

  // Legacy lang info styles (kept for backward compat — no longer rendered)
  langInfoRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10, paddingTop: 8, borderTopWidth: 1, gap: 0 },
  langInfoItem: { flex: 1, alignItems: 'center', gap: 3 },
  langInfoLabel: { fontSize: 9, fontWeight: '700', letterSpacing: 0.7, textTransform: 'uppercase' },
  langInfoValue: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  langInfoValueText: { fontSize: 12, fontWeight: '600' },
  langInfoDivider: { width: 1, height: 28, marginHorizontal: 8 },
});
